### ISSUE TITLE
obs_image.sh - primary beam corrected images are not being made

### ISSUE THREAD

**Issue by gemmaanderson** [PaulHancock/MWA-fast-image-transients#15]
I have just finished imaging the calibrator HydA_121 dataset: 1207582088

obs_image.sh is currently not making primary beam corrected images. beam-MFS files seem to not be generated.

See error in:
/astro/mwasci/phancock/D0009/queue/logs/image_1207582088.e4375426
ls: cannot access 'beam-MFS-*.fits': No such file or directory
/var/spool/slurmd/job4375426/slurm_script: line 77: [[: 0       0       0: syntax error in expression (error token is "0       0")
slurmstepd: error: Exceeded step memory limit at some point.
slurmstepd: error: Exceeded job memory limit at some point.

**Comment by PaulHancock** [comment]
Fixed this bug as of  53165092a6e7be8cee01d7513b8e5b3cc9af86c8
