### ISSUE TITLE
Cotter crashes if the Flagged file has not been generated

### ISSUE THREAD

**Issue by gemmaanderson** [PaulHancock/MWA-fast-image-transients#16]
Cotter crashes if Flagged file does not exist in the MWA database. See:
/astro/mwasci/phancock/D0009/queue/logs/otter_1207602104.e4376542

Also see the error in chained download script:
/astro/mwasci/phancock/D0009/queue/logs/dl_1207602104.e2485635

ls: cannot access '1207602104*.mwaf': No such file or directory
slurmstepd: error: Exceeded step memory limit at some point.
slurmstepd: error: Exceeded job memory limit at some point.

**Comment by PaulHancock** [comment]
Fixed the logic that checks for the number of files.
