### ISSUE TITLE
Use ASVO / manta-ray for download and cottering

### ISSUE THREAD

**Issue by gemmaanderson** [PaulHancock/MWA-fast-image-transients#17]
Recommend using ASVO / manta-ray for all downloading and cottering of our transient datasets. See Natasha's email on 9 May, 2018

**Comment by PaulHancock** [comment]
The scripts have been created and are under testing.

**NOTE**: ASVO is currently not able to download embargoed data, which means we cannot download data from the last 18months! This will change in the future, when the ASVO is upgraded.

**Comment by PaulHancock** [comment]
The functionality of the ASVO client is limited to be not useful for our project because we cannot _yet_ ask for 0.5 second time resolution which is what we have been using for our default. I have put tickets on the manta-ray/ASVO page to have this addressed.

**Comment by PaulHancock** [comment]
tested and working on non embargoed data
