### ISSUE TITLE
workq vs gpuq

### ISSUE THREAD

**Issue by gemmaanderson** [PaulHancock/MWA-fast-image-transients#19]
According to the documentation, the default for all these scripts is to run on the gpuq (which I understand is where all MWA processes are supposed to be run).

However, when I look at the scripts that are generated for calibration, applying calibration and imaging (in the "queue" directory) they all seem to be using the workq as they have the following in the header:
#SBATCH -p workq

The imaging jobs that I currently have running on galaxy also say they are on the workq.

Is the workq now our default?

**Comment by PaulHancock** [comment]
Some of the templates have `workq` in the header, however the queue that the job is submitted to is controlled in the `.sh` scripts using the `-p` command line option. Thus the default queue is still the gpuq.

**Comment by PaulHancock** [comment]
I have updated all the `.tmpl` files to have qpuq in the headers so that this confusion doesn't reoccur.
