### ISSUE TITLE
Download script crashing

### ISSUE THREAD

**Issue by gemmaanderson** [PaulHancock/MWA-fast-image-transients#2]
I am trying to process a calibrator observation of HerA for observations of MAXI J1535 taken on 21 Sept.
% ./bin/obs_dl.sh 1190018416 0 1190018416 HerA

It looks like the download script is crashing when it tries to start running stuff on Galaxy. I got the following errors in dl_1190018416.e2370068

Warning: Permanently added the ECDSA host key for IP address '146.118.80.38' to the list of known hosts.
Permission denied, please try again.
Permission denied, please try again.
Received disconnect from 146.118.80.38 port 22:2: Too many authentication failures
Connection to galaxy closed by remote host.
slurmstepd: error: Exceeded step memory limit at some point.
slurmstepd: error: Exceeded job memory limit at some point.

**Comment by PaulHancock** [comment]
This looks like a problem with the SSH connection between Zeus and galaxy.
If you can log into zeus and then ssh into galaxy without having to confirm anything or enter a password then you have no ssh issues. Otherwise we need to fix your ssh settings.

**Comment by gemmaanderson** [comment]
When on Zeus I do need my password to ssh into Galaxy
