### ISSUE TITLE
Calibrator path has changed

### ISSUE THREAD

**Issue by gemmaanderson** [PaulHancock/MWA-fast-image-transients#20]
Jai has been trying to run obs_calibrate on the HydA observation: 1207582632

The logs complain of the following:
using calibrator model : model-HydA-58comp_withalpha.txt
```
Cannot find calibrator model for HydA
File: /group/mwa/software/MWA_Tools/anoko/mwa-reduce/models/model-HydA-58comp_withalpha.txt not found
```
It looks like the path to the calibrator models has changed. There is now an extra 'anoko' directory in the path:
/group/mwa/software/MWA_Tools/anoko/anoko/mwa-reduce/models

I have told Jai to edit the calibrator path in the created sbatch script manually for the moment.

**Comment by PaulHancock** [comment]
This has been fixed as of 1fd07ce (July 19)
