### ISSUE TITLE
Slurm imaging error 

### ISSUE THREAD

**Issue by gemmaanderson** [PaulHancock/MWA-fast-image-transients#31]
The following error is appearing after cleaning. I am unsure if it is affecting the work flow. See:
image_1217495544.e5048549
image_1217495424.e5048543

```
/var/spool/slurmd/job5048549/slurm_script: line 10: ./functions.sh: No such file or directory
++ awk '{print strftime("%F %T")";",$0; fflush()}'
```

**Comment by PaulHancock** [comment]
This bug has been fixed.
