### ISSUE TITLE
Slurm memory parameter - imaging problem

### ISSUE THREAD

**Issue by gemmaanderson** [PaulHancock/MWA-fast-image-transients#41]
I am running an imaging script "image_1217495184_forselfcal.sh" but I am getting the following error (see logs/image_sc_1217495184.o2951422)

`>>> Could not parse value '-weight' for parameter -abs-mem to a (double-precision) floating point value`

It seems that the path $SLURM_MEM_PER_NODE is actually empty so there is no input float for -abs-mem. Has the path changed?

**Comment by PaulHancock** [comment]
As of 6111ce9 I have fixed this issue so that `image.tmpl` and all other templates now use the `get_mem` function that is defined in `functions.sh`.
