### ISSUE TITLE
Dependency option on scripts no working

### ISSUE THREAD

**Issue by gemmaanderson** [PaulHancock/MWA-fast-image-transients#42]
When I try to run a script on Zeus using the -d option, I get the following error:

`./bin/obs_infield_cal.sh: line 97: exras: unbound variable`

**Comment by gemmaanderson** [comment]
Without using the -d option I still get the "unbound variable" error:

```
> ./bin/obs_infield_cal.sh -a 1217495184
./bin/obs_infield_cal.sh: line 97: depend: unbound variable
```

**Comment by PaulHancock** [comment]
This issue has been fixed.

**Comment by gemmaanderson** [comment]
There is still a similar error, now with an sbatch error:

```
> ./bin/obs_infield_cal.sh -a 1217495184
sbatch: error: Batch job submission failed: Invalid account or account/partition combination specified
./bin/obs_infield_cal.sh: line 109: jobid[3]: unbound variable

```

**Comment by PaulHancock** [comment]
The default queue was being set to `gpuq` which you don't have access to causing the sbatch error.
I have updated the default queue for this script and it should now work as intended.
