### ISSUE TITLE
crop_catalogue.py not found by obs_infield_cal.sh

### ISSUE THREAD

**Issue by gemmaanderson** [PaulHancock/MWA-fast-image-transients#43]
When running obs_infield_cal.sh, it does not seem to know where crop_catalogue.py is located to create cropped_catalogue.fits and local_gleam_model.txt

See logfile: infield_cal_1217495664.e2955888

For those observations for which a local_gleam_model is already calibrated, the infield calibration seems to progress fine.

**Comment by PaulHancock** [comment]
Caused by not having `mwapy` module loaded.
`infield_cal.tmpl` has been updated to load the `mwapy` module and this should fix the issue.
