### ISSUE TITLE
Migration of scripts to Magnus

### ISSUE THREAD

**Issue by gemmaanderson** [PaulHancock/MWA-fast-image-transients#49]
I tried to run an imaging script on Magnus:

`> ./bin/obs_im28s.sh -g pawsey0345 -p 16asec -c 1248917592`

Here are the errors from: im28s_1248917592.e4429953

`cmdModule.c(579):ERROR:50: Cannot open file '/opt/modulefiles/slurm/17.11.9-2' for 'reading'
cmdModule.c(579):ERROR:50: Cannot open file '/pawsey/cle60up05/modulefiles/tools/pawseytools/1.23' for 'reading'
cmdModule.c(579):ERROR:50: Cannot open file '/opt/cray/ari/modulefiles/pdsh/2.27-6.0.5.0_14.2__g70b69a8.ari' for 'reading'
cmdModule.c(579):ERROR:50: Cannot open file '/opt/modulefiles/Base-opts/2.4.123-6.0.5.0_11.2__g6460790.ari' for 'reading'
cmdModule.c(579):ERROR:50: Cannot open file '/opt/cray/ari/modulefiles/rca/2.2.16-6.0.5.0_15.34__g5e09e6d.ari' for 'reading'
`

Here are the errors from: im28s_1248917592.o4429953

`2020-01-10 15:52:11; + An exception occured:
2020-01-10 15:52:11; + >>> CFITSIO reported error when performing IO on file '1248917592-28s-t0000-psf.fits':couldn't create the named file (failed to create new file (already exists?):1248917592-28s-t0000-psf.fits)
2020-01-10 15:52:11; + + + + + + + + + + + + + + + + + + +
`

**Comment by PaulHancock** [comment]
The errors in `im28s_1248917592.e4429953` are due to `source /group/mwa/software/module-reset.sh` and may or may not be related to the cfitsio errors seen later. I'll fix this first.

**Comment by PaulHancock** [comment]
Only some of the templates had been updated with the `newgrp masci` command. The `im28s.tmpl` was not updated and so what is being seen is actually a file permissions error: the directory is owned by `mwasci`, but you can't write to it with group `pawsey0345` (unless you are the owner of the directory, which is Jun in this specific example).

As of 8b35de3 I have now updated all the templates to use the correct newgrp command.

**Comment by PaulHancock** [comment]
The directory that we are testing in: `/home/phancock/D0009/processing/1248917592` is owned by jtian, but has no group write permissions - thus even with the above fix we can't write to this directory.

jtian has some strange default permissions set which will be followed up separately. For now I consider this ticked fixed.
