### ISSUE TITLE
Suggestions for obs_flag_tiles.sh (not urgent)

### ISSUE THREAD

**Issue by gemmaanderson** [PaulHancock/MWA-fast-image-transients#5]
As well as the obs_flag_tiles.sh TODO: "allow flagging file and obsnum to be different", perhaps the calibrator obsid can be specified, allowing the script to go and find that calibrator's tiles_to_flag.txt file. This would make it easier to incorporate into the chain, which already requires you to specify the calibrator.

**Comment by PaulHancock** [comment]
As of f1266d1, you can now use `-f flagfile` to specify any flagging file that you like.
