### ISSUE TITLE
Template SBATCH headers and test scripts

### ISSUE THREAD

**Issue by gemmaanderson** [PaulHancock/MWA-fast-image-transients#50]
Edit all obs_*.sh scripts to copy all user/default header information to all corresponding *.tmpl scripts.

While the resulting script submitted by obs_*.sh will still go to the correct cluster/group/queue, test scripts will not unless those details are specified on the command line. 
It also makes it easier to look back on old processing if the scripts reflect all the chosen processing options that were run at that time.

**Comment by PaulHancock** [comment]
This has now been completed.

All `obs_*.sh` scripts will create a schedule file that contains all the submission information in the sbatch header, such that the script produced when using the `-t` option can be submitted with `sbatch <script>` and expect the same behaviour as the automatic submission (though without the job being logged to our custom database).
