### ISSUE TITLE
obs_flag_tiles.sh bug

### ISSUE THREAD

**Issue by gemmaanderson** [PaulHancock/MWA-fast-image-transients#7]
obs_flag_tiles.sh does not recognise the obsnum_tiles_to_flag.txt file
See the following input and output errors:
> ./bin/obs_flag_tiles.sh 1190018416
flagging file doesn't exist: 
not submitting job

> ./bin/obs_flag_tiles.sh -f processing/1190018416_tiles_to_flag.txt 1190018416
./bin/obs_flag_tiles.sh: line 92: S{sub}: command not found
usage: track_task.py [-h] [--jobid JOBID] [--task TASK]
                     [--submission_time SUBMISSION_TIME]
                     [--start_time START_TIME] [--finish_time FINISH_TIME]
                     [--batch_file BATCH_FILE] [--obs_id OBS_ID]
                     [--stderr STDERR] [--stdout STDOUT]
                     directive
track_task.py: error: argument --jobid: invalid int value: ''
Submitted /astro/mwasci/phancock/D0009/queue/flag_tiles_1190018416.sh as

**Comment by PaulHancock** [comment]
The double slash looks like bad formatting but linux just treats it as one.
The error was a stupid typo on my part `S` instead of `$` in the bash script.
This is now fixed as of 3115492
