### ISSUE TITLE
Documentation on flagging scripts

### ISSUE THREAD

**Issue by gemmaanderson** [PaulHancock/MWA-fast-image-transients#8]
Please have a sentence that describes obs_flag.sh and obs_flag_tiles.sh. It is currently not clear what the difference is between the two scripts. Does the -f command line option require the full path to the file ("ie processing/1obsnum_tiles_to_flag.txt)?

obsnum and obsid are used interchangeably in the documentation for obs_im05s.sh and obs_im28s.sh

**Comment by PaulHancock** [comment]
All fixed as of a16fd1c
The flag scripts now auto-expand your relative path to an absolute path.
So you should write `processing/obsnum_tiles_to_flag.txt`, or you could even store the files elsewhere if you really wanted to.
