### ISSUE TITLE
Metafits file for flagging tiles with >X working dipoles

### ISSUE THREAD

**Issue by gemmaanderson** [PaulHancock/MWA-fast-image-transients#9]
When downloading the MWA dataset, have the option to use a different metafits file that will only flag those tiles with, say, <8 working dipoles.

**Comment by PaulHancock** [comment]
The new version of the metafits files can be downloaded via:
`wget http://mwa-metadata01.pawsey.org.au/metadata/fits?obs_id=${obsnum}\&min_bad_dipoles=5 -O ${obsnum}_metafits.fits`

**Comment by PaulHancock** [comment]
Note: use `max_bad_dipoles` instead of `min_bad_dipoles`

**Comment by PaulHancock** [comment]
actually `min_bad_dipoles` means *for flagging*

**Comment by PaulHancock** [comment]
also, the default is now min_bad=2
